config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :librarians
  resources :books
  resources :authors
  resources :categories
  resources :clients
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
    validates_presence_of :name, message: 'é um campo obrigatório'
    validates_uniqueness_of :name, message: 'já foi cadastrado'
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>
<div class="box box-primary py-5 mr-5">
  <div class="box-body">
    <div class="form-group">
    <%= render 'form', category: @category %>
    </div>
  </div>
</div>

<%= button_to "Show", @category, :class => "btn btn-primary", :style =>"color: white; margin: 5px; float:left;", :method => :get %>
<p style="float: left; padding-top: 12px"> | </p>
<%= button_to "Back", categories_path, :class => "btn btn-default", :style =>"margin: 5px;", :method => :get %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Categories</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <table class="table table-bordered">
      <tbody><tr>
        <th>Name</th>
      </tr>
      <tr>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= link_to 'Show', category %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= button_to "New Category", new_category_path, :class => "btn btn-primary", :style =>"color: white;", :method => :get %>

app/views/categories/new.html.erb
<h1>New Category</h1>
<div class="box box-primary py-5 mr-5">
  <div class="box-body">
    <div class="form-group">
    <%= render 'form', category: @category %>
    </div>
  </div>
</div>

<%= button_to "Back", categories_path, :class => "btn btn-primary", :style =>"color: white;", :method => :get %>

app/views/categories/show.html.erb
<p id="notice"></p>
<section class="invoice">
  <div class="row invoice-info">
    <div class="col-sm-4 invoice-col">
      <b>Name: </b><%= @category.name %><br>
    </div>
  </div>
</section>

<%= button_to "Edit", edit_category_path(@category), :class => "btn btn-primary", :style =>"color: white; margin: 5px; float:left;", :method => :get %>
<p style="float: left; padding-top: 12px"> | </p>
<%= button_to "Back", categories_path, :class => "btn btn-default", :style =>"margin: 5px;", :method => :get %>