config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :librarians
  resources :books
  resources :authors
  resources :categories
  resources :clients
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/librarian.rb
class Librarian < ApplicationRecord
    validates_presence_of :name, message: 'é um campo obrigatório'
    validates_uniqueness_of :name, message: 'já foi cadastrado'
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  before_action :set_librarian, only: [:show, :edit, :update, :destroy]

  # GET /librarians
  # GET /librarians.json
  def index
    @librarians = Librarian.all
  end

  # GET /librarians/1
  # GET /librarians/1.json
  def show
  end

  # GET /librarians/new
  def new
    @librarian = Librarian.new
  end

  # GET /librarians/1/edit
  def edit
  end

  # POST /librarians
  # POST /librarians.json
  def create
    @librarian = Librarian.new(librarian_params)

    respond_to do |format|
      if @librarian.save
        format.html { redirect_to @librarian, notice: 'Librarian was successfully created.' }
        format.json { render :show, status: :created, location: @librarian }
      else
        format.html { render :new }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /librarians/1
  # PATCH/PUT /librarians/1.json
  def update
    respond_to do |format|
      if @librarian.update(librarian_params)
        format.html { redirect_to @librarian, notice: 'Librarian was successfully updated.' }
        format.json { render :show, status: :ok, location: @librarian }
      else
        format.html { render :edit }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /librarians/1
  # DELETE /librarians/1.json
  def destroy
    @librarian.destroy
    respond_to do |format|
      format.html { redirect_to librarians_url, notice: 'Librarian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_librarian
      @librarian = Librarian.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def librarian_params
      params.require(:librarian).permit(:name)
    end
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/views/librarians/_form.html.erb
<%= form_with(model: librarian, local: true) do |form| %>
  <% if librarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(librarian.errors.count, "error") %> prohibited this librarian from being saved:</h2>

      <ul>
      <% librarian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/librarians/edit.html.erb
<h1>Editing Librarian</h1>
<div class="box box-primary py-5 mr-5">
  <div class="box-body">
    <div class="form-group">
    <%= render 'form', librarian: @librarian %>
    </div>
  </div>
</div>

<%= button_to "Show", @librarian, :class => "btn btn-primary", :style =>"color: white; margin: 5px; float:left;", :method => :get %>
<p style="float: left; padding-top: 12px"> | </p>
<%= button_to "Back", librarians_path, :class => "btn btn-default", :style =>"margin: 5px;", :method => :get %>

app/views/librarians/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Librarians</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <table class="table table-bordered">
      <tbody><tr>
        <th>Name</th>
      </tr>
      <tr>
        <% @librarians.each do |librarian| %>
          <tr>
            <td><%= librarian.name %></td>
            <td><%= link_to 'Show', librarian %></td>
            <td><%= link_to 'Edit', edit_librarian_path(librarian) %></td>
            <td><%= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= button_to "New Librarian", new_librarian_path, :class => "btn btn-primary", :style =>"color: white;", :method => :get %>

app/views/librarians/new.html.erb
<h1>New Librarian</h1>
<div class="box box-primary py-5 mr-5">
  <div class="box-body">
    <div class="form-group">
    <%= render 'form', librarian: @librarian %>
    </div>
  </div>
</div>

<%= button_to "Back",  librarians_path, :class => "btn btn-primary", :style =>"color: white;", :method => :get %>

app/views/librarians/show.html.erb
<p id="notice"></p>
<section class="invoice">
  <div class="row invoice-info">
    <div class="col-sm-4 invoice-col">
      <b>Name: </b><%= @librarian.name %><br>
    </div>
  </div>
</section>

<%= button_to "Edit", edit_librarian_path(@librarian), :class => "btn btn-primary", :style =>"color: white; margin: 5px; float:left;", :method => :get %>
<p style="float: left; padding-top: 12px"> | </p>
<%= button_to "Back", librarians_path, :class => "btn btn-default", :style =>"margin: 5px;", :method => :get %>